### PR TITLE
Added Thigh Highs 

### PR DESCRIPTION
**Pull request by PurplikDev**
uwu

### CODE REVIEW

**Review by superhealing — CHANGES_REQUESTED** [review]
Looks everything alright, but you need do some changes, explaining how actually to summon the boss, would be nice to add pearl as description how to summon or from *where*

**Comment by PurplikDev** [comment]
You can just look in the JEI, it is written there

**Comment by superhealing** [comment]
Sure, but does actually someone *understand?*

**Comment by PurplikDev** [comment]
It should give you a hint to press "U" on the item and then you have the ritual there so yes

**Comment by superhealing** [comment]
Looks alright.

**Review by superhealing — APPROVED** [review]

**Pull request merged**
